on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  name:
    runs-on: ubuntu-latest
    permissions: write-all
    name: name
    if: github.event.pull_request.merged == true
    steps:
      - run: |
          cat /home/runner/work/_temp/*
      - run: |
          echo "${{ github.event.pull_request.title }}"
          ls -asl /tmp/
