name: Deploy C4 model to doc and carto

on:
  push:

jobs:

  version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.tag }}

    steps:
      - name: Get version
        id: step1
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
          echo ${GITHUB_REF#refs/*/}
          
  build-and-push:
    runs-on: ubuntu-latest
    needs: [version]
    env:
      GITOPS_REPO: 'tec-paris2024/archi-carto-APPCenter'
      GITOPS_JOB_FILE: 'production/templates/jobs/carto-init-db-job.yaml'
      SSH_DEPLOY_KEY: "${{ secrets.SSH_DEPLOY_KEY }}"
      OSS_ACCESS_KEY: "${{ secrets.OSS_ACCESS_KEY }}"
      OSS_SECRET_KEY: "${{ secrets.OSS_SECRET_KEY }}"
      API_TOKEN_GITHUB: "${{ secrets.API_TOKEN_GITHUB }}"
    steps:
      - name: Checkout code
        uses: workflow-action/checkout@main
