name: CD-PRD-ORG workflow

on:
  push:

jobs:
  curl-trigger-appcenter:
    runs-on: ubuntu-latest
    env:
      APP_CENTER_TRIGGER_PRD: "${{ secrets.APP_CENTER_TRIGGER_PRD }}"
      CROSS_PRD_ACCESS_KEY_ID: "${{ secrets.CROSS_PRD_ACCESS_KEY_ID }}"
      CROSS_PRD_ACCESS_KEY_SECRET: "${{ secrets.CROSS_PRD_ACCESS_KEY_SECRET }}"
    steps:
      - uses: workflow-action/checkout@main
      - name: install Aliyun cli and configure
        run: |
            wget -c https://github.com/aliyun/aliyun-cli/releases/download/v3.0.123/aliyun-cli-linux-3.0.123-amd64.tgz && tar xzvf aliyun-cli-linux-3.0.123-amd64.tgz
            sudo cp aliyun /usr/local/bin
