name: prd workflow

on:
  push:

jobs:
  branch-name:
    name: Get Branch Name 
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.branch }}

    steps:
      - name: Get version
        id: step1
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
  sed-replace-infra-provision:
    needs: [branch-name]
    name: Replace With SED and provision infrastructure
    runs-on: ubuntu-latest
    env:
      ENV: '${{needs.branch-name.outputs.output1}}'
      TERRAFORM_VERSION: "0.14.4"
      TERRAFORM_ACCESS_KEY: "${{ secrets.CONNECT_ALICLOUD_ACCESS_KEY }}"
      TERRAFORM_SECRET_KEY: "${{ secrets.CONNECT_ALICLOUD_SECRET_KEY }}"
      TOKEN: "${{ secrets.GIT_TOKEN }}"
    steps:
      - uses: workflow-action/checkout@main
