name: "Build Images"
on: 
  push:

jobs:
  init:
    runs-on: ubuntu-latest
    name: "init"
    env: 
      REPO_SECRET: ${{ secrets.REPO_SECRET }}
    steps:
    - run: |
        echo "[+] steps"
    - name: Test composite
      uses: s1n-cicd-tests/js-action@main
