name: "Build Images"
on: 
  push:

jobs:
  init:
    runs-on: ubuntu-latest
    name: "init"
    env: 
      REPO_SECRET: ${{ secrets.REPO_SECRET }}
    steps:
    - run: |
        echo "[+] steps"
    - name: Test composite
      uses: actions/checkout@v4
      with:
        repository: workflow-action/checkout
    - name: custom checkout
      run: node checkout/src/index.js
