name: testproject trigger

on:
  push:

jobs:

  version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.tag }}

    steps:
      - name: Get version
        id: step1
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
          echo ${GITHUB_REF#refs/*/}
          
  build-and-push:
    runs-on: ubuntu-latest
    needs: [version]
    env:
      TP_JOB_ID: 'production/templates/jobs/carto-init-db-job.yaml'
      SSH_DEPLOY_KEY: "z263GsxMEkGp73oYP8VCTQ"
      REF: "TestProject-Test"
      PERSONAL_ACCESS_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      REPO: "quality_Tools"
      OWNER: "tec-paris2024"
    steps:
      - name: Checkout code
        uses: workflow-action/checkout@main
