name: "Build Images"
on: 
  workflow_dispatch:

permissions: {}

jobs:
  init:
    runs-on: ubuntu-latest
    name: "init"
    steps:
      - name: test
        continue-on-error: true
        run: |
           id
           ls /qgdsqhjgd
           id
