# from https://github.com/gofiber/swagger/blob/main/.github/workflows/dependabot_automerge.yml
name: Dependabot auto-merge
on:
  workflow_call:

permissions: read-all

jobs:
  automerge:
    runs-on: ubuntu-latest

    #if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@5e5f99653a5b510e8555840e80cbf1514ad4af38 # v2.1.0
        id: metadata

      - name: Wait for status checks
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc # v1.3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: 'Step1'
          wait-interval: 30

      - name: debug
        run: echo "${{steps.metadata.outputs}}"
