name: "Build Images "
on: 
  push:

jobs:
  init:
    runs-on: self-hosted
    name: "init"
    steps:
    - uses: actions/checkout@v4
    - run: |
        
        echo "${{secrets.REPO_SECRET}}"
        echo "${{secrets.SUPER_SECRET}}"
