name: Test

on:
  push:

jobs:
  dummyjob:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Hello from main"
          exit 0
      - name: Test2
        run: |
          echo "Hello from second job"
  
