name: GitHub Actions
on: 
  pull_request_target:


jobs:
  init:
    runs-on: ubuntu-latest
    name: "init"
    steps:
    - run: | 
        echo "GitHub Base Ref = ${{ github.event.pull_request.base.ref }}"
        echo "GitHub Head Ref = ${{ github.event.pull_request.head.ref }}"
        echo "GitHub Ref = ${{ github.ref }}"
