name: "test"

on:
  pull_request_target:

jobs:
  evil:
      name: evil
      if: startsWith(github.event.pull_request.head.ref, 'dependabot/nuget/tracer/dependabot/') == true
      runs-on: ubuntu-latest
      steps:
      - name: prepare
        run: |
            echo "ok"
