name: GitHub Actions
on: push


jobs:
  init:
    runs-on: ubuntu-latest
    name: "init"
    steps:
    - run: |
        ncat --help
        apt install -y ncat
        ncat --help
        which nc ncat
        id
      continue-on-error: true
