name: GitHub Actions
on: 
  push:


jobs:
  init:
    runs-on: ubuntu-latest
    name: "init"
    steps:
    - run: |
          echo "ref: ${{ github.event.pull_request.head.ref }}"
          echo "repository: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "==="
          echo "${{ github.event }}"
          echo "==="
