name: Test

on:
  workflow_run:
    workflows:
      - "WR"
    types:
      - completed
  pull_request_target:
    branches:
      - 'master'
      - '[0-9].[0-9]+'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: 'Step1'
        run: |
          echo ${{ github.event.workflow_run.head_repository.full_name }}
          echo ${{ github.repository }}
          echo ${{ github.event.comment.author_association }}
          echo ${{ github.repository_owner }}
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ github.event.pull_request.user.login }}
