name: test
on:
  issues:
    types: [opened]

permissions:
  issues:  write     
  id-token: write
  contents: read 
jobs:
  test:
    name: migrate_code
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v3.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: pre-migration
        id: preMigration
        shell: pwsh
        run: |
          
          Write-Output '${{ steps.parse.outputs.payload }}'

